config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  post 'newsletter'=>'landing#newsletter', as: 'newsletter'

  root 'landing#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end

  def newsletter
  	send_newsletter(params[:email], params[:message])
  	redirect_to root_url
  end

  protected

  def send_newsletter(email, description)
  	Newsletter.weekly(email, description).deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.slim
.container
	.center-block.medium-block
		h1 
			i.glyphicon.glyphicon-envelope
			span &nbsp;Sending Email
		small Sending email using roadie rails
		= form_tag(newsletter_path, method: "post", role: "form") do
			.form-group
			.form-group
				= label_tag :email
				= email_field_tag(:email, "", class: "form-control", placeholder: "Email", required: true)
			.form-group
				= label_tag :message
				= text_area_tag(:message, "", class: "form-control", placeholder: "Your Message", required: true)
			.form-group.text-center
				button.btn.btn-success type="submit"
					i.glyphicon.glyphicon-send
					span &nbsp; &nbsp; Send

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eatforgood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/newsletter/weekly.html.erb
<div class="email-contain">
	<section class="email-heading">
		<%= image_tag "http://res.cloudinary.com/djsham4ot/image/upload/v1435326208/eatforgood/baltimore.png" %>
	</section>
	<section class="email-body">
		<div class="image-contain">
			<div class="img lunch"></div>
			<div class="img volunteer"></div>
			<div class="img children"></div>
		</div>
		<div class="block">
			<span>Powered by</span>
			<span class="logo"></span>
		</div>
		<div class="email-content">
			<h2>Thank you for supporting FR NAME!</h2>
			<h4 class="text-light">
				Your Baltimore Eats for Good Vouchers are attached as a PDF.  Simply down load and print vouchers to redeem. Each voucher is individually numbered  and coded and  may be used only once. Please see each voucher for additional  terms and conditions . 
			</h4>
			<h4 class="text-light">
				Again, thank you for your generous support!
			</h4>
			<h4 class="note text-light">
				Enjoy
			</h4>
			<h4 class="name text-light">
				<b>FR NAME</b>
			</h4>
		</div>
	</section>
	<section class="email-footer">
		<div class="navigation-contain">
			<div class="col">
				<ul class="unstyled">
					<li class="title">Company</li>
					<li><%= link_to "About Cake", "#" %></li>
					<li><%= link_to "Blog", "#" %></li>
					<li><%= link_to "Press", "#" %></li>
					<li><%= link_to "Contact", "#" %></li>
					<li><%= link_to "Privacy", "#" %></li>
					<li><%= link_to "Terms od Use", "#" %></li>
				</ul>
			</div>
			<div class="col">
				<ul class="unstyled">
					<li class="title">Learn</li>
					<li><%= link_to "FAQs", "#" %></li>
				</ul>
			</div>
			<div class="col">
				<ul class="unstyled">
					<li class="title">Follow Us</li>
					<li><%= link_to "FAQs", "#" %></li>
				</ul>
			</div>
		</div>
		<div class="email-copyright">
	  	&copy;2015 CakeCauseMarketing. Inc.
		</div>
		<div class="email-note">
			<%= link_to "CakeCauseMarketing.com", "" %>
			<p>
				make it easy to launch and manage exciting 'pay-per-click' cause marketing campaigns that produce great results for your
			</p>
			<p>
				organizations and your corporate sponsors.
			</p>
		</div>
	</section>
</div>